@startuml fig-2
interface Linda 
class CentralizedLinda {
 ArrayListSync<Tuple> database
 ArrayListSync<Event> callbacks
 Object lock
   void write(Tuple t)
   Tuple take(Tuple template)
   Tuple read(Tuple template)
   Tuple tryTake(Tuple template)
   Tuple tryRead(Tuple template)
   Collection<Tuple> takeAll(Tuple template)
   Collection<Tuple> readAll(Tuple template)
   void eventRegister(eventMode mode, eventTiming timing, Tuple template, Callback callback)
   void debug(String prefix)
   void debug(String prefix, PrintStream ps)
   void runCallBacks()
}
Linda<|-- CentralizedLinda
@enduml